### PR TITLE
feat: add input_field_placeholder field

### PR DESCRIPTION
**Pull request by MahdiyarGHD**

### CODE REVIEW

**Comment by WebPajooh** [comment]
Hello and thanks for your pull request.

As you see in the construct method, we pass the options as arguments there and don't have any setters for other options. Why not to move it to the constructor to be simply like others?

**Review by muhammadmp97 — CHANGES_REQUESTED** [review]
Hello and thanks for your pull request. @MahdiyarGHD 

As you see in the `__construct()` method, we pass the options as arguments there and don't have any setters for other options. Why not to move it to the constructor to be simply like others?

**Comment by MahdiyarGHD** [comment]
I guess it's fixed now

**Comment by muhammadmp97** [comment]
Please review my commit. @MahdiyarGHD 
We also need to update the ReplyKeyboardTest.

**Review by muhammadmp97 — APPROVED** [review]
I think it's ready now!

**Pull request merged**
